package HelloApp;

/*This interface contains the methods sayHello() and shutdown().
The IDL-to-Java mapping puts all of the operations defined on the 
IDL interface into this file, which is shared by both the stubs and skeletons.*/

/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* mi�rcoles 13 de enero de 2016 13:46:27 Hora de Colombia
*/

public interface HelloOperations 
{
  String sayHello ();

  // This line is an operation statement.
  void shutdown ();
} // interface HelloOperations
