package HelloApp;

/*
This interface contains the Java version of our IDL interface. The Hello.java 
interface extends org.omg.CORBA.Object, providing standard CORBA object 
functionality. It also extends the HelloOperations interface 
and org.omg.CORBA.portable.IDLEntity.
*/

/**
* HelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* mi�rcoles 13 de enero de 2016 13:46:27 Hora de Colombia
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
